### ISSUE TITLE
follow_anything.py won't end

### ISSUE THREAD

**Issue by Alex-fishred** [alaamaalouf/FollowAnything#2]
I am currently executing
python follow_anything.py  --desired_height 240 --desired_width 320 --path_to_video /home/islab/FollowAnything/FollowAnything/example_videos/car_following.avi --save_images_to outputs/  --detect dino --redetect_by dino --use_sam --tracker aot --queries_dir /home/islab/FollowAnything/FollowAnything/queries/toy_car_following --desired_feature 0 --plot_visualizations 

But after running the video, the program will stop working, which means the program will not end automatically. Is this normal?
The final terminal output is as shown below 
![image](https://github.com/alaamaalouf/FollowAnything/assets/76515591/7e6d5f9d-40aa-43c5-835a-7fdb7d74c29d)

**Comment by alaamaalouf** [comment]
I have fixed this behavior to make the system stops once the offline video is done.

However, we currently keep this for online streaming, as sometimes reading frames might be delayed due to communication issues. Thus, currently, for online streaming, the program could be stopped manually. We will work on improving this.
